//WARNING: This file contains swear words, racial/cultural slurs, and other offensive language!

//Filter Levels:
//1: LOW
//2: MODERATE
//3: STRICT
//4: This means that the word is treated as a slur and is always blocked regardless of filtering settings.

module.exports = [
    blockedWords= [ //The list of blocked words.
        {word: "anus", substitution: "butt", filterLevel: 3},
        {word: "arse", substitution: "butt", filterLevel: 3},
        {word: "ass", substitution: "butt", filterLevel: 3},
        {word: "bastard", substitution: "illegitimate child", filterLevel: 2},
        {word: "bitch", substitution: "female dog", filterLevel: 2},
        {word: "blowjob", substitution: "blooper", filterLevel: 2},
        {word: "boner", substitution: "erection", filterLevel: 2},
        {word: "chesticle", substitution: "breast", filterLevel: 3},
        {word: "cock", substitution: "thingy", filterLevel: 3},
        {word: "cocks", substitution: "thingies", filterLevel: 3},
        {word: "dick", substitution: "thingy", filterLevel: 2},
        {word: "dicks", substitution: "thingies", filterLevel: 2},
        {word: "cunt", substitution: "girl thingy", filterLevel: 2},
        {word: "cunts", substitution: "girl thingies", filterLevel: 2}, 
        {word: "damn", substitution: "darn", filterLevel: 3},
        {word: "handjob", substitution: "Midas Touch", filterLevel: 2},
        {word: "hell", substitution: "heck", filterLevel: 3},
        {word: "goddamn", substitution: "gosh darn", filterLevel: 3},
        {word: "fap", substitution: "self-pleasure", filterLevel: 2},
        {word: "faps", substitution: "self-pleasures", filterLevel: 2},
        {word: "fapping", substitution: "self-pleasuring", filterLevel: 2},
        {word: "masturbate", substitution:"self-pleasure", filterLevel: 2},
        {word: "masturbation", substitution: "self-pleasure", filterLevel: 2},
        {word: "masturbates", substitution: "self-pleasures", filterLevel: 2},
        {word: "masturbator", substitution: "self-pleasurer", filterLevel: 2},
        {word: "masturbating", substitution: "self-pleasuring", filterLevel: 2},       
        {word: "wank", substitution: "self-pleasure", filterLevel: 2},
        {word: "wanks", substitution: "self-pleasures", filterLevel: 2},
        {word: "wanker", substitution: "self-pleasurer", filterLevel: 2},
        {word: "dildo", substitution: "pleasure toy", filterLevel: 2},
        {word: "condom", substitution: "male birth control", filterLevel: 3},
        {word: "tampon", substitution: "female hygiene product", filterLevel: 3},
        {word: "viagra", substitution: "male enhancement drugs", filterLevel: 3},
        {word: "nigger", substitution: "African-American", filterLevel: 4},
        {word: "nigga", substitution: "African-American", filterLevel: 4},
        {word: "jap", substitution: "Japanese person", filterLevel: 4},
        {word: "piss", substitution: "urine", filterLevel: 3},
        {word: "pissed", substitution: "urinated", filterLevel: 3},
        {word: "pisses", substitution: "urinates", filterLevel: 3},
        {word: "pissing", substitution: "urinating", filterLevel: 3},
        {word: "shit", substitution: "feces", filterLevel: 2},
        {word: "shits", substitution: "defecates", filterLevel: 2},
        {word: "shitload", substitution: "lot", filterLevel: 2},
        {word: "shitloads", substitution: "lots", filterLevel: 2},
        {word: "shitting", substitution: "defecating", filterLevel: 2},
        {word: "bullshit", substitution: "hogwash", filterLevel: 2},
        {word: "bs", substitution: "hogwash", filterLevel: 3}, 
        {word: "crappy", substitution: "bad", filterLevel: 3},
        {word: "craps", substitution: "defecates", filterLevel: 3},
        {word: "crap", substitution: "feces", filterLevel: 3},
        {word: "crapped", substitution: "defecated", filterLevel: 3},
        {word: "crapping", substitution: "defecating", filterLevel: 3},
        {word: "bullcrap", substitution: "hogwash", filterLevel: 3},
        {word: "crapton", substitution: "lot", filterLevel: 3},
        {word: "crap-ton", substitution: "lot", filterLevel: 3},
        {word: "shat", substitution: "defecated", filterLevel: 2},
        {word: "fuck", substitution: "freak", filterLevel: 1},
        {word: "fucked", substitution: "screwed", filterLevel: 1},
        {word: "fucker", substitution: "meanie", filterLevel: 1},
        {word: "fuckers", substitution: "meanies", filterLevel: 1},
        {word: "fucking", substitution: "freaking", filterLevel: 1},
        {word: "motherfucker", substitution: "meanie", filterLevel: 1},
        {word: "motherfuckers", substitution: "meanies", filterLevel: 1},
        {word: "motherfucking", substitution: "dumb", filterLevel: 1},
        {word: "clusterfuck", substitution: "dumb person", filterLevel: 1},
        {word: "buttfuck", substitution: "cornhole", filterLevel: 1},
        {word: "butt-fuck", substitution: "cornhole", filterLevel: 1},
        {word: "fuckery", substitution: "meanness", filterLevel: 1},
        {word: "fuckup", substitution: "screwup", filterLevel: 1},
        {word: "fuck-up", substitution: "screw-up", filterLevel: 1},
        {word: "boned", substitution: "screwed", filterLevel: 3},
        {word: "porn", substitution: "adult entertainment", filterLevel: 1},
        {word: "pron", substitution: "adult entertainment", filterLevel: 1},
        {word: "pornography", substitution: "adult entertainment", filterLevel: 1},
        {word: "pornographic", substitution: "adult", filterLevel: 1},   
        {word: "xxx", substitution: "inappropriate", filterLevel: 1},
        {word: "shitty", substitution: "bad", filterLevel: 2},
        {word: "asshole", substitution: "meanie", filterLevel: 3},
        {word: "tit", substitution: "breast", filterLevel: 2},
        {word: "tits", substitution: "breasts", filterLevel: 2},
        {word: "dickwad", substitution: "meanie", filterLevel: 2},
        {word: "assholery", substitution: "meanness", filterLevel: 3},
        {word: "scum", substitution: "meanie", filterLevel: 3},
        {word: "scums", substitution: "meanies", filterLevel: 3},
        {word: "cum", substitution: "feel aroused", filterLevel: 2},
        {word: "cumming", substitution: "feeling aroused", filterLevel: 2},
        {word: "cums", substitution: "feels aroused", filterLevel: 2},
        {word: "sodomite", substitution: "homosexual woman", filterLevel: 4},
        {word: "retard", substitution: "handicapped person", filterLevel: 4},
        {word: "retarded", substitution: "handicapped", filterLevel: 4},
        {word: "tard", substitution: "handicapped person", filterLevel: 4},
        {word: "tards", substitution: "handicapped people", filterLevel: 4},
	{word: "kill", substitution: "unalive", filterLevel: 3},
	{word: "die", substitution: "unalive", filterLevel: 3},
	{word: "suicide", substitution: "unalive", filterLevel: 3},
	{word: "pandemic", substitution: "panini", filterLevel: 3}
    ]
]